### ISSUE TITLE
PG::ConnectionBad

### ISSUE THREAD

**Issue by Kostykins** [ckumar1/smart-fridge-rails#1]
Merging the Master Branch to Add-HTML-CSS-Pages branch causes this error when running 'rails server' and loading local host

This is the description:
"could not connect to server: No such file or directory Is the server running locally and accepting connections on Unix domain socket "/tmp/.s.PGSQL.5432"?"

I saw the GemFile was changed to always use pg for every enviornment and I think that may be the issue?

I can no longer test my pages :( halp

**Comment by ghost** [comment]
Do you have postgres installed on your machine? If you install it from brew I don't think there should be any additional configuration. However you may have to remove the

**Comment by ghost** [comment]
Sorry.. Sending from my phone.

... Remove the line password: 'pantryfridge' from the database.yml file. 

I'll try to see what the specific cause of the error is in the meantime
