### ISSUE TITLE
Unclear UI on food screen

### ISSUE THREAD

**Issue by jaltekruse** [ckumar1/smart-fridge-rails#11]
Most of the screen is just blank space, I did know you wanted me to click on the + symbol, but I would recommend some kind of text to tell users what to do. First picture in gallery, but I assume this is just what it is supposed to look like

http://imgur.com/a/XBuuQ

**Comment by jaltekruse** [comment]
Severity: minor

**Comment by Kostykins** [comment]
Fixed: The screen now tells the user to click the "+" button if the user has no food items.
